import { NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

interface Params {
    params: Promise<{
        videoId: string
    }>
}

export async function GET(request: Request, { params }: Params) {
    try {
        const session = await getServerSession(authOptions)
        if (!session?.user?.id) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
        }

        const { videoId } = await params

        // Get creator ID
        const creator = await prisma.creator.findUnique({
            where: { userId: session.user.id },
            select: { id: true }
        })

        // Fetch video asset with related data
        const videoAsset = await prisma.videoAsset.findFirst({
            where: {
                id: videoId,
                OR: [
                    { creatorId: creator?.id }, // Creator can see their own
                    { status: 'READY' } // Anyone can see ready videos (check course enrollment separately)
                ]
            },
            include: {
                qualities: {
                    select: {
                        id: true,
                        quality: true,
                        resolution: true,
                        bitrate: true,
                        url: true,
                        codec: true
                    },
                    orderBy: {
                        bitrate: 'desc'
                    }
                },
                subtitles: {
                    select: {
                        id: true,
                        language: true,
                        label: true,
                        fileUrl: true,
                        isDefault: true,
                        isAutoGenerated: true
                    }
                },
                chapters: {
                    select: {
                        id: true,
                        title: true,
                        titleAr: true,
                        startTime: true,
                        endTime: true,
                        thumbnail: true,
                        position: true
                    },
                    orderBy: {
                        position: 'asc'
                    }
                },
                course: {
                    select: {
                        id: true,
                        title: true,
                        thumbnail: true
                    }
                },
                lesson: {
                    select: {
                        id: true,
                        title: true,
                        order: true
                    }
                }
            }
        })

        if (!videoAsset) {
            return NextResponse.json(
                { error: 'Video not found' },
                { status: 404 }
            )
        }

        // Get user's progress if authenticated
        let progress = null
        if (session?.user?.id) {
            progress = await prisma.videoProgress.findUnique({
                where: {
                    userId_videoAssetId: {
                        userId: session.user.id,
                        videoAssetId: videoId
                    }
                },
                select: {
                    currentTime: true,
                    duration: true,
                    progress: true,
                    completed: true,
                    lastWatched: true
                }
            })
        }

        // Get engagement stats
        const [commentsCount, reactionsCount] = await Promise.all([
            prisma.videoComment.count({
                where: {
                    videoAssetId: videoId,
                    isHidden: false
                }
            }),
            prisma.videoReaction.count({
                where: { videoAssetId: videoId }
            })
        ])

        // Get user's reaction if authenticated
        let userReaction = null
        if (session?.user?.id) {
            userReaction = await prisma.videoReaction.findUnique({
                where: {
                    videoAssetId_userId: {
                        videoAssetId: videoId,
                        userId: session.user.id
                    }
                },
                select: {
                    type: true
                }
            })
        }

        // Calculate processing progress if still processing
        let processingProgress = null
        if (videoAsset.status === 'PROCESSING') {
            const metadata = videoAsset.metadata as any || {}
            processingProgress = {
                stage: metadata.processingStage || 'transcoding',
                percentage: metadata.processingPercentage || 50,
                estimatedTimeRemaining: metadata.estimatedTimeRemaining || 120 // seconds
            }
        }

        return NextResponse.json({
            video: {
                id: videoAsset.id,
                title: videoAsset.title,
                titleAr: videoAsset.titleAr,
                description: videoAsset.description,
                descriptionAr: videoAsset.descriptionAr,
                status: videoAsset.status,
                thumbnailUrl: videoAsset.thumbnailUrl,
                duration: videoAsset.duration,
                aspectRatio: videoAsset.aspectRatio,
                maxResolution: videoAsset.maxResolution,
                frameRate: videoAsset.frameRate,
                fileSize: videoAsset.fileSize,
                createdAt: videoAsset.createdAt,
                updatedAt: videoAsset.updatedAt,
                course: videoAsset.course,
                lesson: videoAsset.lesson
            },
            qualities: videoAsset.qualities,
            subtitles: videoAsset.subtitles,
            chapters: videoAsset.chapters,
            progress,
            engagement: {
                commentsCount,
                reactionsCount,
                userReaction: userReaction?.type || null
            },
            processingProgress,
            playbackUrl: videoAsset.status === 'READY' && videoAsset.qualities.length > 0
                ? videoAsset.qualities[0].url
                : null
        })
    } catch (error) {
        console.error('Error fetching video status:', error)
        return NextResponse.json(
            { error: 'Failed to fetch video status' },
            { status: 500 }
        )
    }
}
